package com.rgds.ultimate.shell;

import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

/** Request state outlives its view. Applying checks both identity and the user's edit revision. */
final class TextCandidates {
    enum State { REQUESTED, SEARCHING, NO_CANDIDATES, MATCHED_WITHOUT_REQUESTED_LANGUAGE, SOURCE_UNAVAILABLE, NETWORK_ERROR, TIMEOUT, CANCELLED, PREVIEW_READY, APPLYING, APPLIED, APPLY_FAILED, INTERRUPTED }
    enum Source { BANGUMI, WIKIPEDIA_EN }
    private static final ExecutorService worker=Executors.newSingleThreadExecutor(r->new Thread(r,"text-candidates"));
    private static final ScheduledExecutorService timer=Executors.newSingleThreadScheduledExecutor(r->new Thread(r,"text-deadline"));
    private static final Handler main=new Handler(Looper.getMainLooper());
    private static final Map<String,Request> latest=new ConcurrentHashMap<>();
    static final class Request {
        final String id=UUID.randomUUID().toString(),gameId,workId,locale,query;final GameEntry game;final Source source;final long editRevision,created=System.currentTimeMillis();
        final MetadataManager metadata;final SourceHttp http=new SourceHttp();final List<Runnable> listeners=new CopyOnWriteArrayList<>();
        volatile State state=State.REQUESTED;volatile String reason=UiStrings.msg("ui_d784f1abb480");volatile List<JSONObject> choices=Collections.emptyList();volatile boolean stopped,finished;
        Request(Activity a,GameEntry game,String query,Source source){this.game=game;gameId=game.gameId;this.query=query;this.source=source;metadata=MetadataManager.get(a);OfflineCatalog.Head head=metadata.catalog.head(gameId);workId=head==null?"":head.workId;locale=LocaleSettings.content();editRevision=metadata.overrideCopy(gameId).optLong("updatedAt");}
        String sourceName(){return source==Source.BANGUMI?UiStrings.msg("ui_29bc72c04e12"):"Wikipedia · English";}
        synchronized boolean move(State next,String message){if(stopped)return false;state=next;reason=message;persist(this);main.post(()->{for(Runnable listener:listeners)listener.run();metadata.notifyTaskUi();});return true;}
        synchronized void cancel(State next,String message){if(stopped||finished)return;move(next,message);stopped=true;http.cancel();}
        boolean current(){OfflineCatalog.Head h=metadata.catalog.head(gameId);return !stopped&&locale.equals(LocaleSettings.content())&&latest.get(gameId)==this&&editRevision==metadata.overrideCopy(gameId).optLong("updatedAt")&&workId.equals(h==null?"":h.workId);}
        JSONObject json(){try{return new JSONObject().put("requestId",id).put("gameId",gameId).put("workId",workId).put("language",locale).put("editRevision",editRevision).put("source",source.name()).put("query",query).put("created",created).put("updated",System.currentTimeMillis()).put("state",state.name()).put("reason",reason).put("candidateCount",choices.size());}catch(JSONException e){throw new IllegalStateException(e);}}
    }
    private static synchronized void persist(Request r){if(PerfTrace.isEnabled())android.util.Log.i("TwinGridText","request="+r.id+" game="+r.gameId+" locale="+r.locale+" source="+r.source+" state="+r.state+" candidates="+r.choices.size()+" uid="+android.os.Process.myUid());SharedPreferences p=r.metadata.contextForUi().getSharedPreferences("text_requests_v1",0);try{JSONArray old=new JSONArray(p.getString("recent","[]")),next=new JSONArray().put(r.json());for(int n=0;n<old.length()&&next.length()<20;n++)if(!old.getJSONObject(n).optString("requestId").equals(r.id))next.put(old.getJSONObject(n));p.edit().putString("recent",next.toString()).apply();}catch(JSONException ignored){}}
    static void history(Activity a){try{JSONArray rows=new JSONArray(a.getSharedPreferences("text_requests_v1",0).getString("recent","[]"));if(rows.length()==0){UiDialogs.text(a,UiStrings.msg("ui_f60717abaa3a"),UiStrings.msg("ui_2bddbec702f5"));return;}String[] labels=new String[rows.length()];for(int n=0;n<rows.length();n++){JSONObject r=rows.getJSONObject(n);Request live=latest.get(r.optString("gameId"));if((live==null||!live.id.equals(r.optString("requestId")))&&Arrays.asList("REQUESTED","SEARCHING","APPLYING").contains(r.optString("state")))r.put("state","INTERRUPTED").put("reason",UiStrings.msg("ui_436c4edd1c0f"));labels[n]=r.optString("query")+" · "+r.optString("language")+" · "+label(State.valueOf(r.optString("state")));}GapUi.menu(a,UiStrings.msg("ui_f60717abaa3a"),UiStrings.msg("ui_e7fd12affb10"),labels,n->{JSONObject row=rows.optJSONObject(n);Request live=latest.get(row.optString("gameId"));if(live!=null&&live.id.equals(row.optString("requestId")))show(a,live);else UiDialogs.text(a,labels[n],row.optString("reason")+UiStrings.msg("ui_83f3af69098a"));});}catch(Exception e){UiDialogs.text(a,UiStrings.msg("ui_f60717abaa3a"),UiStrings.msg("ui_47b675fcb07c"));}}
    static void chooseSource(Activity a,GameEntry g){MetadataManager m=MetadataManager.get(a);OfflineCatalog.Head h=m.catalog.head(g.gameId);String initial=h==null?(m.info(g.gameId).title.isEmpty()?GameDisplay.name(g,m):m.info(g.gameId).title):h.original;
        Source[] sources=LocaleSettings.content().equals("en")?new Source[]{Source.WIKIPEDIA_EN,Source.BANGUMI}:new Source[]{Source.BANGUMI,Source.WIKIPEDIA_EN};
        GapUi.menu(a,UiStrings.msg("ui_a925027f048c"),UiStrings.msg("ui_f446d799ff74")+LocaleSettings.content()+UiStrings.msg("ui_7ac4d6a91f7c"),new String[]{sources[0]==Source.BANGUMI?UiStrings.msg("ui_bf86632624a6"):UiStrings.msg("ui_677a75f6a341"),sources[1]==Source.BANGUMI?UiStrings.msg("ui_bf86632624a6"):UiStrings.msg("ui_677a75f6a341"),UiStrings.msg("ui_83a44e563667")},n->{if(n==2){history(a);return;}GapUi.query(a,UiStrings.msg("ui_b0206a4d0caf"),initial,q->search(a,g,q,sources[n]));});
    }
    static void search(Activity a,GameEntry g,String query){search(a,g,query,LocaleSettings.content().equals("en")?Source.WIKIPEDIA_EN:Source.BANGUMI);}
    static void search(Activity a,GameEntry g,String query,Source source){if(query.trim().isEmpty()||query.length()>200){UiDialogs.text(a,UiStrings.msg("ui_6bafc2ce74d8"),UiStrings.msg("ui_4b3fbd4121fa"));return;}
        Request r=new Request(a,g,query.trim(),source),old=latest.put(g.gameId,r);if(old!=null)old.cancel(State.CANCELLED,UiStrings.msg("ui_7c4e957a3609"));persist(r);show(a,r);
        SharedPreferences policy=a.getApplicationContext().getSharedPreferences("text_candidate_policy",0);
        ScheduledFuture<?> deadline=timer.schedule(()->r.cancel(State.TIMEOUT,UiStrings.msg("ui_da97628c2ca6")),35,TimeUnit.SECONDS);
        worker.execute(()->{try{if(r.stopped)return;r.move(State.SEARCHING,UiStrings.msg("ui_e09acbc20337")+r.sourceName());if(policy.getLong("retryAt:"+source.name(),0)>System.currentTimeMillis()){r.move(State.SOURCE_UNAVAILABLE,UiStrings.msg("ui_3e6216ae864d"));return;}
            List<JSONObject> rows=source==Source.BANGUMI?bangumi(r,policy):wikipedia(r,policy);if(r.stopped)return;r.choices=Collections.unmodifiableList(rows);
            if(rows.isEmpty())r.move(State.NO_CANDIDATES,UiStrings.msg("ui_17a4fbf932c9"));
            else if(rows.stream().noneMatch(c->c.optString("language").equals(r.locale)&&GameDescription.usable(c.optString("text"))))r.move(State.MATCHED_WITHOUT_REQUESTED_LANGUAGE,UiStrings.msg("ui_fb2c345f6352"));
            else r.move(State.PREVIEW_READY,UiStrings.msg("ui_729046f8eb38"));
        }catch(java.net.SocketTimeoutException e){r.move(State.TIMEOUT,UiStrings.msg("ui_8b53375b71be"));}
        catch(java.io.InterruptedIOException e){r.move(State.TIMEOUT,UiStrings.msg("ui_8b53375b71be"));}
        catch(SourceFailure e){r.move(State.SOURCE_UNAVAILABLE,e.getMessage());}
        catch(JSONException e){r.move(State.SOURCE_UNAVAILABLE,UiStrings.msg("ui_fc4309c95619"));}
        catch(Exception e){if(!r.stopped)r.move(State.NETWORK_ERROR,UiStrings.msg("ui_7eae9ed98192")+e.getClass().getSimpleName()+UiStrings.msg("ui_55a437b6e7fe"));}
        finally{r.finished=true;deadline.cancel(false);}});
    }
    private static final class SourceFailure extends Exception {SourceFailure(String m){super(m);}}
    private static JSONObject read(SourceHttp.Result response,Request r,SharedPreferences p)throws Exception{if(response.status!=200){long retry=RemotePolicy.retryAt(response.status,response.retryAfter,System.currentTimeMillis());p.edit().putLong("retryAt:"+r.source.name(),retry).apply();throw new SourceFailure(UiStrings.msg("ui_24cdb6a2713d")+response.status+UiStrings.msg("ui_72e92bfd6731"));}if(!response.type.toLowerCase(Locale.ROOT).contains("json"))throw new SourceFailure(UiStrings.msg("ui_8583bf80ca2c"));return new JSONObject(new String(response.body,java.nio.charset.StandardCharsets.UTF_8));}
    private static List<JSONObject> bangumi(Request r,SharedPreferences policy)throws Exception{JSONObject post=new JSONObject().put("keyword",r.query).put("sort","match").put("filter",new JSONObject().put("type",new JSONArray().put(4)));JSONArray data=read(r.http.request("/v0/search/subjects?limit=5&offset=0",post),r,policy).getJSONArray("data");List<JSONObject> result=new ArrayList<>();
        for(int n=0;n<data.length()&&!r.stopped;n++){if(n>0)Thread.sleep(850);if(r.stopped)break;r.move(State.SEARCHING,UiStrings.msg("ui_3f48e7476393")+(n+1)+" / "+data.length());JSONObject full=read(r.http.request("/v0/subjects/"+data.getJSONObject(n).getInt("id"),null),r,policy);if(!BangumiSource.nds(full))continue;String text=GameDescription.cleanParagraphs(full.optString("summary"));result.add(candidate(full.optString("name_cn")+" / "+full.optString("name"),text,"https://bgm.tv/subject/"+full.getInt("id"),"Bangumi / CC BY-SA 3.0",String.join(" / ",BangumiSource.field(full,"平台")),BangumiSource.variantReview(full)));}return result;
    }
    private static List<JSONObject> wikipedia(Request r,SharedPreferences policy)throws Exception{String url="https://en.wikipedia.org/w/api.php?action=query&format=json&formatversion=2&generator=search&gsrnamespace=0&gsrlimit=5&gsrsearch="+android.net.Uri.encode(r.query+" Nintendo DS")+"&prop=extracts%7Cinfo&exintro=1&explaintext=1&exlimit=5&inprop=url";JSONObject root=read(r.http.publicText(url),r,policy);if(root.has("error"))throw new SourceFailure(UiStrings.msg("ui_fce9bdb6725b"));JSONObject q=root.optJSONObject("query");JSONArray pages=q==null?null:q.optJSONArray("pages");List<JSONObject> result=new ArrayList<>();if(pages==null)return result;for(int n=0;n<pages.length();n++){JSONObject page=pages.getJSONObject(n);String text=GameDescription.cleanParagraphs(page.optString("extract"));if(!text.contains("Nintendo DS")||!text.toLowerCase(Locale.ROOT).contains("game"))continue;boolean mixed=text.matches("(?s).*(PlayStation|Xbox|Nintendo 3DS|Wii|PlayStation Portable).*" );result.add(candidate(page.optString("title"),text,page.optString("fullurl"),"Wikipedia / CC BY-SA 4.0","Nintendo DS (source introduction)",mixed));}return result;}
    private static JSONObject candidate(String name,String text,String url,String source,String platform,boolean variants)throws JSONException{return new JSONObject().put("name",name).put("text",text).put("language",GameDescription.language(text)).put("url",url).put("source",source).put("platforms",platform).put("variantReview",variants).put("fetchedAt",System.currentTimeMillis()).put("textSHA256",MetadataManager.hash(text));}
    static String label(State s){switch(s){case REQUESTED:return UiStrings.msg("ui_d784f1abb480");case SEARCHING:return UiStrings.msg("ui_130b9a21a9ab");case NO_CANDIDATES:return UiStrings.msg("ui_5784a1b4ae38");case MATCHED_WITHOUT_REQUESTED_LANGUAGE:return UiStrings.msg("ui_e1915a0200e0");case SOURCE_UNAVAILABLE:return UiStrings.msg("ui_6b9df175c462");case NETWORK_ERROR:return UiStrings.msg("ui_88c035ff99b6");case TIMEOUT:return UiStrings.msg("ui_0145ec462b1b");case CANCELLED:return UiStrings.msg("ui_a37778f17c5f");case PREVIEW_READY:return UiStrings.msg("ui_f63cd1ec1c37");case APPLYING:return UiStrings.msg("ui_570d60206779");case INTERRUPTED:return UiStrings.msg("ui_55822afa174d");case APPLIED:return UiStrings.msg("ui_1bd91a7d0c53");default:return UiStrings.msg("ui_6309a3bb5ba4");}}
    private static void show(Activity a,Request r){LinearLayout box=new LinearLayout(a);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(16,4,16,4);box.addView(GapUi.caption(a,r.query+"\n"+r.sourceName()+" · "+r.locale));TextView status=GapUi.caption(a,"");status.setMinLines(3);box.addView(status);ProgressBar progress=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);progress.setIndeterminate(true);box.addView(progress,new LinearLayout.LayoutParams(-1,10));
        AlertDialog d=new ShellDialogBuilder(a).setTitle(UiStrings.msg("ui_6875f3ce0ea5")).setView(box).setPositiveButton(UiStrings.msg("ui_e3e0faa1e395"),null).setNeutralButton(UiStrings.msg("ui_78e3f326fb5b"),null).setNegativeButton(UiStrings.msg("ui_6f88b3b88f3e"),null).create();
        Runnable bind=()->{if(!d.isShowing()||a.isFinishing())return;status.setText(label(r.state)+"\n"+r.reason);boolean active=r.state==State.REQUESTED||r.state==State.SEARCHING;progress.setVisibility(active?View.VISIBLE:View.GONE);d.getButton(-1).setEnabled(!r.stopped&&!r.choices.isEmpty());d.getButton(-3).setEnabled(!active);d.getButton(-2).setText(UiStrings.render(active?UiStrings.msg("ui_6f88b3b88f3e"):UiStrings.msg("ui_dae2ca72e96a")));ShellDialogBuilder.help(d,r.query+"\n"+r.sourceName()+"\n"+label(r.state)+"\n\n"+r.reason);};
        d.setOnDismissListener(x->r.listeners.remove(bind));d.setOnCancelListener(x->r.cancel(State.CANCELLED,UiStrings.msg("ui_16967f66e88d")));d.show();r.listeners.add(bind);bind.run();
        d.getButton(-2).setOnClickListener(v->{r.cancel(State.CANCELLED,UiStrings.msg("ui_16967f66e88d"));d.dismiss();});
        d.getButton(-3).setOnClickListener(v->GapUi.menu(a,UiStrings.msg("ui_82795f7a16d0"),r.reason,new String[]{UiStrings.msg("ui_5bb56202f5be"),UiStrings.msg("ui_0b0fcbca3f64"),UiStrings.msg("ui_2fa6a18b4490"),UiStrings.msg("ui_337fa2bfda84")},n->{if(n==0){d.dismiss();search(a,r.game,r.query,r.source);}else if(n==1)chooseSource(a,r.game);else if(n==2)GapUi.lookup(a,r.game,true);else GapUi.editText(a,r.game,"description");}));
        d.getButton(-1).setOnClickListener(v->GapUi.menu(a,UiStrings.msg("ui_e3cda824413b"),UiStrings.msg("ui_1000aa43d539"),r.choices.stream().map(c->c.optString("name")+" · "+c.optString("language")).toArray(String[]::new),n->preview(a,r,r.choices.get(n))));
    }
    private static void preview(Activity a,Request r,JSONObject c){String text=c.optString("text"),locale=c.optString("language");String body=c.optString("name")+UiStrings.msg("ui_1a6371b05a88")+c.optString("platforms")+UiStrings.msg("ui_3470cca033be")+locale+"\n\n"+text+"\n\n"+c.optString("url")+"\n"+c.optString("source")+(c.optBoolean("variantReview")?UiStrings.msg("ui_3d41860fb577"):UiStrings.msg("ui_ff302300f5e4"));
        AlertDialog d=new ShellDialogBuilder(a).setTitle(UiStrings.msg("ui_0eff9f589d97")).setMessage(body).setPositiveButton(UiStrings.msg("ui_1b9743ac7a0d")+locale,null).setNegativeButton(UiStrings.msg("ui_2cd0f3be8738"),null).setNeutralButton(UiStrings.msg("ui_6623d2a971b4"),(x,n)->GapUi.editText(a,r.game,"description")).create();d.show();ShellDialogBuilder.gamePreview(d,r.game,TaskPresentation.msg("17")+c.optString("name"));d.getButton(-1).setEnabled(GameDescription.usable(text)&&locale.equals(r.locale)&&Arrays.asList("zh","en").contains(locale)&&!c.optBoolean("variantReview"));
        d.getButton(-1).setOnClickListener(v->{if(!locale.equals(r.locale)||!r.current()){r.move(State.APPLY_FAILED,UiStrings.msg("ui_4ffde288db5f"));UiDialogs.text(a,UiStrings.msg("ui_38abb602c89a"),r.reason);return;}try{JSONObject source=new JSONObject(c.toString());source.remove("text");source.put("requestId",r.id).put("confirmedAt",System.currentTimeMillis()).put("confirmedForGameId",r.gameId);JSONObject patch=new JSONObject().put(LocaleSettings.field("confirmedText",locale),text).put(LocaleSettings.field("confirmedKind",locale),"REFERENCE").put(LocaleSettings.field("confirmedTextSource",locale),source);r.move(State.APPLYING,UiStrings.msg("ui_b81e6a8cfb6f"));d.getButton(-1).setEnabled(false);r.metadata.editFieldsChecked(r.gameId,patch,Collections.emptyList(),r.editRevision,r::current,(ok,message)->{r.move(ok?State.APPLIED:State.APPLY_FAILED,message);d.getButton(-1).setEnabled(!ok);if(a.isFinishing()||a.isDestroyed())return;if(ok){d.dismiss();UiDialogs.text(a,UiStrings.msg("ui_df0297c214e9"),locale+" · "+message);}else UiDialogs.text(a,UiStrings.msg("ui_42969ebf2803"),message);});}catch(JSONException e){r.move(State.APPLY_FAILED,UiStrings.msg("ui_e757f80baa21"));UiDialogs.text(a,UiStrings.msg("ui_42969ebf2803"),r.reason);}});
    }
}
