package com.rgds.ultimate.shell;
/** Physical pixels, inside the page beginning at y=40. */
final class UiMetrics {
    static final int LEFT=24,WIDTH=592,PAGE_TOP=40,BUTTON=44,FOOTER=384,ROW=60,ROW_STEP=64,ROWS=5;
    static final int LIBRARY_ROWS=4,ROW_HEIGHT=60,ROW_PITCH=64,ROW_TEXT_Y=4,ROW_TEXT_HEIGHT=48,ROW_ICON_X=16,ROW_ICON_Y=14,ROW_TITLE_X=60,ROW_RIGHT=12,CARD_INSET=16,CARD_VERTICAL=12;
    static final int LIBRARY_CONTENT_TOP=100,LIBRARY_CONTENT_BOTTOM=356,GENRE_COLUMNS=3,GENRE_ROWS=5,GENRE_PITCH=56,GENRE_HEIGHT=52;
    static final int LIBRARY_FILTER_WIDTH=164,LIBRARY_CLEAR_WIDTH=40,LIBRARY_CONTROL_GAP=8;
    static final int LIBRARY_FILTER_X=LEFT+WIDTH-LIBRARY_FILTER_WIDTH,LIBRARY_CLEAR_X=LIBRARY_FILTER_X-LIBRARY_CONTROL_GAP-LIBRARY_CLEAR_WIDTH;
    static final int LIBRARY_NAV_TOP=4,LIBRARY_SCOPE_TOP=60,LIBRARY_STATUS_RESERVED=80,LIBRARY_STATUS_HEIGHT=36,EMPTY_TO_STATUS_GAP=12;
}
